MallocNanoZone=0
USER=aleksandr
COMMAND_MODE=unix2003
__CFBundleIdentifier=com.microsoft.VSCode
PATH=/Users/aleksandr/.vscode/extensions/ms-python.python-2025.0.0-darwin-arm64/python_files/deactivate/zsh:/Users/aleksandr/Yandex.Disk.localized/project/venv/bin:/usr/local/bin:/Users/aleksandr/.vscode/extensions/ms-python.python-2025.0.0-darwin-arm64/python_files/deactivate/zsh:/Users/aleksandr/Yandex.Disk.localized/project/venv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.13/bin:/Library/Frameworks/Python.framework/Versions/3.12/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/aleksandr/.vscode/extensions/ms-python.python-2025.0.0-darwin-arm64/python_files/deactivate/zsh:/Users/aleksandr/Yandex.Disk.localized/project/venv/bin
LOGNAME=aleksandr
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.gri9sR9PUS/Listeners
HOME=/Users/aleksandr
SHELL=/bin/zsh
TMPDIR=/var/folders/t2/84z8__7s71j8c055yfnl6jp80000gn/T/
__CF_USER_TEXT_ENCODING=0x1F5:0x7:0x31
XPC_SERVICE_NAME=0
XPC_FLAGS=0x0
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
SHLVL=1
PWD=/Users/aleksandr/Yandex.Disk.localized/project
OLDPWD=/Users/aleksandr/Yandex.Disk.localized/project
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_REPOSITORY=/opt/homebrew
INFOPATH=/opt/homebrew/share/info:/opt/homebrew/share/info:
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.97.2
LANG=ru_RU.UTF-8
COLORTERM=truecolor
PYDEVD_DISABLE_FILE_VALIDATION=1
DEBUGPY_ADAPTER_ENDPOINTS=/Users/aleksandr/.vscode/extensions/ms-python.debugpy-2025.0.1-darwin-arm64/.noConfigDebugAdapterEndpoints/endpoint-1c2fc11dbb0f803a.txt
BUNDLED_DEBUGPY_PATH=/Users/aleksandr/.vscode/extensions/ms-python.debugpy-2025.0.1-darwin-arm64/bundled/libs/debugpy
VIRTUAL_ENV=/Users/aleksandr/Yandex.Disk.localized/project/venv
VIRTUAL_ENV_PROMPT=venv
GIT_ASKPASS=/private/var/folders/t2/84z8__7s71j8c055yfnl6jp80000gn/T/AppTranslocation/5A09AC9C-4E20-4CAB-8DC3-A4610A8536D9/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
VSCODE_GIT_ASKPASS_NODE=/private/var/folders/t2/84z8__7s71j8c055yfnl6jp80000gn/T/AppTranslocation/5A09AC9C-4E20-4CAB-8DC3-A4610A8536D9/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
VSCODE_GIT_ASKPASS_MAIN=/private/var/folders/t2/84z8__7s71j8c055yfnl6jp80000gn/T/AppTranslocation/5A09AC9C-4E20-4CAB-8DC3-A4610A8536D9/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
VSCODE_GIT_IPC_HANDLE=/var/folders/t2/84z8__7s71j8c055yfnl6jp80000gn/T/vscode-git-5f24ec3c9c.sock
VSCODE_INJECTION=1
ZDOTDIR=/Users/aleksandr
USER_ZDOTDIR=/Users/aleksandr
TERM=xterm-256color
VSCODE_PROFILE_INITIALIZED=1
PS1=venv%n@%m %1~ %# 
_=/usr/bin/python3
SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
CPATH=/usr/local/include
LIBRARY_PATH=/usr/local/lib
MANPATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man:/Library/Developer/CommandLineTools/usr/share/man:/Library/Developer/CommandLineTools/Toolchains/XcodeDefault.xctoolchain/usr/share/man:
